Repository Shining-Jicheon-Stars/yjg-ts-react-frontend, pull requests merged in 2024-02, with the labels that each got.

#6 Feat：管理者関連API適用
  src/assets/schoolImg/logo_header.png
  src/assets/schoolImg/school.jpg
  src/assets/schoolImg/simbol.png
  src/assets/schoolImg/test.jpg
  src/assets/sidebarImg/admin.png
  src/components/Header.tsx
  src/components/Sidebar.tsx
  src/components/auth/AuthBg.tsx
  src/components/auth/FindMyAccountForm.tsx
  src/components/auth/JoinForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/sidebar/SidePowerModal.tsx
  src/components/sidebar/Sidebar.tsx
  src/pages/Main.tsx
  src/services/customAxios.ts
  src/types/login.d.ts
  src/utils/regex.tsx
Labels: ✨ Feat

#8 Feat: サイドバー機能の実装
  package-lock.json
  package.json
  src/App.tsx
  src/assets/sidebarImg/admin.png
  src/components/auth/LoginForm.tsx
  src/components/sidebar/SidePowerModal.tsx
  src/components/sidebar/Sidebar.tsx
  src/constants/powerList.tsx
  src/icons/AdminIcon.tsx
  src/icons/BusIcon.tsx
  src/icons/DropDown.tsx
  src/icons/MasterIcon.tsx
  src/icons/RestaurantIcon.tsx
  src/icons/SalonIcon.tsx
  src/index.tsx
  src/pages/Main.tsx
  src/pages/Mypage.tsx
  src/recoil/UserDataAtiom.tsx
  src/types/adminList.d.ts
  src/types/login.d.ts
Labels: ✨ Feat

#9 Feat: ログアウト, マイ情報のパスワードチェック, マイ情報の参照と情報更新の実装
  src/components/auth/FindMyAccountForm.tsx
  src/components/auth/FormInput.tsx
  src/components/auth/JoinForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/mypage/MypageForm.tsx
  src/components/mypage/PasswordConfirmation.tsx
  src/components/sidebar/SidePowerModal.tsx
  src/components/sidebar/Sidebar.tsx
  src/constants/powerList.tsx
  src/pages/Main.tsx
  src/pages/Mypage.tsx
  src/recoil/UserDataAtiom.tsx
  src/types/auth.d.ts
  src/types/sidebarList.d.ts
Labels: ✨ Feat

#11 Feat: 管理者の会員登録承認・拒否機能と全ユーザー管理機能の実装
  src/App.tsx
  src/components/auth/LoginForm.tsx
  src/components/master/Management.tsx
  src/components/master/MasterMain.tsx
  src/components/master/UserList.tsx
  src/icons/CheckIcon.tsx
  src/icons/CloseIcon.tsx
  src/pages/Master.tsx
  src/recoil/UserDataAtiom.tsx
  src/services/customAxios.ts
  src/types/adminList.d.ts
  src/types/auth.d.ts
  src/types/master.d.ts
Labels: ✨ Feat

#12 Feat: CODEOWNERS生成
  .github/CODEOWNERS
Labels: ✨ Feat

#13 Chore: CODEOWNERSを修正
  .github/CODEOWNERS
  .github/auto_assign.yml
  .github/workflows/pr_assignee.yml
Labels: ✨ Feat

#15 Feat: カレンダー追加と日付データ取得、予約確定者と予約待ちリストの表示
  package-lock.json
  package.json
  src/App.tsx
  src/components/salon/CountCard.tsx
  src/components/salon/PriceCorrection.tsx
  src/components/salon/ReservationList.tsx
  src/components/salon/UnreservedList.tsx
  src/constants/powerList.tsx
  src/pages/Salon.tsx
  src/pages/SalonPending.tsx
  src/pages/SalonPrice.tsx
  src/recoil/UserDataAtiom.tsx
  src/styles/calender.tsx
  src/types/auth.d.ts
  src/types/calendar.d.ts
  src/types/salon.d.ts
Labels: ✨ Feat

#16 Feat: ID探しAPI, ログインページに戻るボタン Rename: ログインページのフォルダ
  src/App.tsx
  src/components/auth/FindMyAccountForm.tsx
  src/components/auth/GetResult.tsx
  src/components/auth/JoinForm.tsx
  src/pages/auth/FindMyAccount.tsx
  src/pages/auth/FindResult.tsx
  src/pages/auth/Join.tsx
  src/pages/auth/Login.tsx
Labels: ✨ Feat, 💱Rename

#17 Refactor: APIリファクタリングとページのdiv要素の高さ調整
  src/components/auth/JoinForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/master/Management.tsx
  src/components/master/MasterMain.tsx
  src/components/master/UserList.tsx
  src/components/mypage/MypageForm.tsx
  src/components/mypage/PasswordConfirmation.tsx
  src/components/sidebar/Sidebar.tsx
  src/pages/Main.tsx
  src/pages/Mypage.tsx
  src/types/auth.d.ts
  src/types/master.d.ts
Labels: ♻ Refactor

#18 Feat: 美容室ページの価格表管理、予約リスト確認、営業時間設定機能の追加
  src/App.tsx
  src/components/salon/CateGoryList.tsx
  src/components/salon/PriceCorrection.tsx
  src/components/salon/ReservationList.tsx
  src/components/salon/UnreservedList.tsx
  src/icons/PlusIcon.tsx
  src/pages/SalonPending.tsx
  src/pages/salon/Salon.tsx
  src/pages/salon/SalonPending.tsx
  src/pages/salon/SalonPrice.tsx
  src/styles/calender.tsx
  src/styles/index.css
Labels: ✨ Feat

#20 Feat: 行政のメインページ, A/Sページ Refactor: 行政関連ページの整理
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header.tsx
  src/components/admin/AdminMain.tsx
  src/components/admin/RepairList.tsx
  src/components/auth/JoinForm.tsx
  src/components/master/Management.tsx
  src/components/master/UserList.tsx
  src/components/post/PostCardSlider.tsx
  src/components/post/ReadPost.tsx
  src/components/salon/CateGoryList.tsx
  src/components/salon/CountCard.tsx
  src/components/salon/ReservationList.tsx
  src/components/salon/UnreservedList.tsx
  src/components/sidebar/Sidebar.tsx
  src/constants/powerList.tsx
  src/icons/CloseIcon.tsx
  src/icons/ImageIcon.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/Repair.tsx
  src/pages/post/Reading.tsx
  src/styles/index.css
  src/styles/post.tsx
Labels: ✨ Feat, ♻ Refactor

#21 Feat: 外泊外出ページ, 会議室ページ, バス時刻表ページ
  src/App.tsx
  src/components/admin/BusManagement.tsx
  src/components/admin/CheckStay.tsx
  src/components/admin/ChoiceList.tsx
  src/components/admin/RoomReservation.tsx
  src/constants/powerList.tsx
  src/icons/PeopleIcon.tsx
  src/pages/admin/BusTimeTable.tsx
  src/pages/admin/MeetingRoom.tsx
  src/pages/admin/StayOut.tsx
Labels: ✨ Feat

#22 Feat: 美容室APIの接続
  src/components/salon/CateGoryList.tsx
  src/components/salon/PriceCorrection.tsx
  src/components/salon/PriceTag.tsx
  src/components/salon/ServiceList.tsx
  src/components/salon/UnreservedList.tsx
  src/icons/CloseIcon.tsx
  src/icons/PlusIcon.tsx
  src/icons/PriceTag.tsx
  src/pages/salon/SalonPrice.tsx
  src/types/salon.d.ts
Labels: ✨ Feat

#23 Feat: お知らせの読み書き機能の追加Develop
  package-lock.json
  package.json
  src/App.tsx
  src/components/admin/AdminMain.tsx
  src/components/master/Management.tsx
  src/components/master/UserList.tsx
  src/components/post/Editor.tsx
  src/components/post/PostImg.tsx
  src/components/post/WritePost.tsx
  src/components/salon/ReservationList.tsx
  src/pages/post/Writing.tsx
  src/types/calendar.d.ts
  src/types/master.d.ts
  src/types/post.d.ts
Labels: ✨ Feat

#24 Refactor: メインコンテナとしてコンポーネントを作成
  src/components/MainContainer.tsx
  src/pages/Master.tsx
  src/pages/Mypage.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/BusTimeTable.tsx
  src/pages/admin/Repair.tsx
  src/pages/admin/StayOut.tsx
  src/pages/post/Reading.tsx
  src/pages/post/Writing.tsx
  src/pages/salon/Salon.tsx
  src/pages/salon/SalonPending.tsx
  src/pages/salon/SalonPrice.tsx
Labels: ♻ Refactor
