Repository Shining-Jicheon-Stars/yjg-ts-react-frontend, pull requests merged in 2024-04, with the labels that each got.

#37 refactor: 全体のデザインを一新
  src/components/Header.tsx
  src/components/MainContainer.tsx
  src/components/admin/as/RepairList.tsx
  src/components/admin/bus/BusCategoryList.tsx
  src/components/admin/bus/BusManagement.tsx
  src/components/admin/bus/ChoiceList.tsx
  src/components/admin/main/AdminMain.tsx
  src/components/admin/main/ModifyPost.tsx
  src/components/admin/main/ReadPost.tsx
  src/components/admin/main/WritePost.tsx
  src/components/admin/overNight/CheckStay.tsx
  src/components/admin/overNight/ReadAbsence.tsx
  src/components/admin/room/RoomReservation.tsx
  src/components/admin/room/RoomState.tsx
  src/components/auth/FindMyAccountForm.tsx
  src/components/auth/GetResult.tsx
  src/components/auth/JoinForm.tsx
  src/components/master/MasterMain.tsx
  src/components/master/UserList.tsx
  src/components/mypage/MypageForm.tsx
  src/components/mypage/PasswordConfirmation.tsx
  src/components/post/Editor.tsx
  src/components/post/page/Pagination.tsx
  src/components/post/page/SearchBar.tsx
  src/components/restaurant/main/RestaurantMain.tsx
  src/components/restaurant/main/TodayPlan.tsx
  src/components/salon/CountCard.tsx
  src/components/salon/PriceCorrection.tsx
  src/components/salon/ReservationList.tsx
  src/components/salon/SalonCategoryList.tsx
  src/components/salon/SetBusinessTime.tsx
  src/components/salon/UnreservedList.tsx
  src/components/sidebar/Sidebar.tsx
  src/constants/powerList.tsx
  src/pages/Main.tsx
  src/styles/calender.tsx
Labels: ✒ Design, ♻ Refactor

#38 feat: AS掲示板へのコメント機能追加, バス路線図の編集機能追加, 美容院の価格表編集機能追加
  src/components/admin/as/ReadAS.tsx
  src/components/admin/as/comment/CommentList.tsx
  src/components/admin/as/comment/Comments.tsx
  src/components/admin/bus/BusScheduleList.tsx
  src/components/salon/SalonServiceList.tsx
  src/types/admin.d.ts
  src/types/salon.d.ts
Labels: ✨ Feat

#39 refactor: ユーザー権限APIの変更に伴うコードのリファクタリング
  src/components/auth/LoginForm.tsx
  src/components/master/OverallUser.tsx
  src/recoil/UserDataAtiom.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/Routing.tsx
  src/types/auth.d.ts
Labels: ♻ Refactor

#41 refactor: 全体デザインの変更とリファクタリングを実施
  src/assets/close.png
  src/components/MainContainer.tsx
  src/components/admin/as/ReadAS.tsx
  src/components/admin/as/comment/CommentList.tsx
  src/components/admin/as/comment/Comments.tsx
  src/components/admin/bus/BusCategoryList.tsx
  src/components/admin/bus/BusManagement.tsx
  src/components/admin/bus/BusScheduleList.tsx
  src/components/admin/main/AdminMain.tsx
  src/components/admin/main/ModifyPost.tsx
  src/components/admin/main/ReadPost.tsx
  src/components/admin/main/WritePost.tsx
  src/components/admin/overNight/ReadAbsence.tsx
  src/components/admin/room/RoomReservation.tsx
  src/components/admin/room/RoomState.tsx
  src/components/auth/FindMyAccountForm.tsx
  src/components/auth/JoinForm.tsx
  src/components/master/MasterMain.tsx
  src/components/master/OverallUser.tsx
  src/components/master/UserList.tsx
  src/components/mypage/MypageForm.tsx
  src/components/mypage/PasswordConfirmation.tsx
  src/components/post/Editor.tsx
  src/components/post/page/Pagination.tsx
  src/components/salon/PriceCorrection.tsx
  src/components/salon/ReservationList.tsx
  src/components/salon/SalonCategoryList.tsx
  src/components/salon/SalonServiceList.tsx
  src/components/salon/SetBusinessTime.tsx
  src/components/salon/UnreservedList.tsx
  src/components/sidebar/Sidebar.tsx
  src/icons/SendIcon.tsx
  src/types/admin.d.ts
  src/types/restaurant.d.ts
  src/utils/formatCurrency.tsx
  src/utils/formatPhoneNum.tsx
Labels: ♻ Refactor

#42 Feat: releaseワークフローを生成
  .github/workflows/add_pull_request_assignee.yml
  .github/workflows/create_release.yml
  release-note.md
Labels: ✨ Feat

#43 refactor: カスタムAPIのリファクタリング, feat: ローディングページの追加, パスワード探索機能の追加
  src/components/LoadingPage.tsx
  src/components/admin/as/ReadAS.tsx
  src/components/admin/as/RepairList.tsx
  src/components/admin/as/comment/CommentList.tsx
  src/components/admin/as/comment/Comments.tsx
  src/components/admin/bus/BusCategoryList.tsx
  src/components/admin/bus/BusManagement.tsx
  src/components/admin/bus/BusScheduleList.tsx
  src/components/admin/main/AdminMain.tsx
  src/components/admin/main/ModifyPost.tsx
  src/components/admin/main/ReadPost.tsx
  src/components/admin/main/WritePost.tsx
  src/components/admin/overNight/CheckStay.tsx
  src/components/admin/overNight/ReadAbsence.tsx
  src/components/admin/room/RoomReservation.tsx
  src/components/admin/room/RoomState.tsx
  src/components/auth/FindMyAccountForm.tsx
  src/components/auth/GetResult.tsx
  src/components/auth/JoinForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/master/MasterMain.tsx
  src/components/master/OverallUser.tsx
  src/components/mypage/MypageForm.tsx
  src/components/mypage/PasswordConfirmation.tsx
  src/components/restaurant/SemesterMeal.tsx
  src/components/restaurant/WeekendMeal.tsx
  src/components/restaurant/dietPlan/DietPlanManagement.tsx
  src/components/restaurant/dietPlan/ModalAddPlan.tsx
  src/components/restaurant/main/ApplicationSettings.tsx
  src/components/restaurant/main/RestaurantMain.tsx
  src/components/restaurant/main/WeekendApplication.tsx
  src/components/restaurant/main/applicationSet/AccountSettings.tsx
  src/components/restaurant/main/applicationSet/ApplicationSettings.tsx
  src/components/salon/PriceCorrection.tsx
  src/components/salon/PriceTag.tsx
  src/components/salon/ReservationList.tsx
  src/components/salon/SalonCategoryList.tsx
  src/components/salon/SalonServiceList.tsx
  src/components/salon/SetBusinessTime.tsx
  src/components/salon/UnreservedList.tsx
  src/components/sidebar/Sidebar.tsx
  src/pages/Main.tsx
  src/recoil/UserDataAtiom.tsx
  src/routes/ProtectedRoute.tsx
  src/services/customAxios.ts
  src/types/auth.d.ts
Labels: ✨ Feat, ♻ Refactor

#44 Test: デプロイテスト
  src/assets/close.png
  src/components/LoadingPage.tsx
  src/components/MainContainer.tsx
  src/components/admin/as/ReadAS.tsx
  src/components/admin/as/RepairList.tsx
  src/components/admin/as/comment/CommentList.tsx
  src/components/admin/as/comment/Comments.tsx
  src/components/admin/bus/BusCategoryList.tsx
  src/components/admin/bus/BusManagement.tsx
  src/components/admin/bus/BusScheduleList.tsx
  src/components/admin/main/AdminMain.tsx
  src/components/admin/main/ModifyPost.tsx
  src/components/admin/main/ReadPost.tsx
  src/components/admin/main/WritePost.tsx
  src/components/admin/overNight/CheckStay.tsx
  src/components/admin/overNight/ReadAbsence.tsx
  src/components/admin/room/RoomReservation.tsx
  src/components/admin/room/RoomState.tsx
  src/components/auth/FindMyAccountForm.tsx
  src/components/auth/GetResult.tsx
  src/components/auth/JoinForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/master/MasterMain.tsx
  src/components/master/OverallUser.tsx
  src/components/master/UserList.tsx
  src/components/mypage/MypageForm.tsx
  src/components/mypage/PasswordConfirmation.tsx
  src/components/post/Editor.tsx
  src/components/post/page/Pagination.tsx
  src/components/restaurant/SemesterMeal.tsx
  src/components/restaurant/WeekendMeal.tsx
  src/components/restaurant/dietPlan/DietPlanManagement.tsx
  src/components/restaurant/dietPlan/ModalAddPlan.tsx
  src/components/restaurant/main/ApplicationSettings.tsx
  src/components/restaurant/main/RestaurantMain.tsx
  src/components/restaurant/main/WeekendApplication.tsx
  src/components/restaurant/main/applicationSet/AccountSettings.tsx
  src/components/restaurant/main/applicationSet/ApplicationSettings.tsx
  src/components/salon/PriceCorrection.tsx
  src/components/salon/PriceTag.tsx
  src/components/salon/ReservationList.tsx
  src/components/salon/SalonCategoryList.tsx
  src/components/salon/SalonServiceList.tsx
  src/components/salon/SetBusinessTime.tsx
  src/components/salon/UnreservedList.tsx
  src/components/sidebar/Sidebar.tsx
  src/icons/SendIcon.tsx
  src/pages/Main.tsx
  src/recoil/UserDataAtiom.tsx
  src/routes/ProtectedRoute.tsx
  src/services/customAxios.ts
  src/types/admin.d.ts
  src/types/auth.d.ts
  src/types/restaurant.d.ts
  src/utils/formatCurrency.tsx
  src/utils/formatPhoneNum.tsx
Labels: 🧪 Test

#45 feat: 食事申込者リスト機能の追加, 食事申込期間設定機能の追加
  src/components/Header.tsx
  src/components/auth/GetResult.tsx
  src/components/mypage/PasswordConfirmation.1.tsx
  src/components/restaurant/SemesterMeal.tsx
  src/components/restaurant/main/WeekendApplication.tsx
  src/components/restaurant/main/applicationSet/ApplicationSettings.tsx
  src/components/restaurant/main/applicationSet/ManualSettings.tsx
  src/components/restaurant/main/applicationSet/SemesterManualSettings.tsx
  src/components/restaurant/main/applicationSet/WeekendManualSettings.tsx
  src/components/restaurant/semesterStatus/SemesterList.tsx
  src/components/restaurant/semesterStatus/SemesterMeal.tsx
  src/components/restaurant/weekendStatus/WeekendList.tsx
  src/components/restaurant/weekendStatus/WeekendMeal.tsx
  src/hook/useSideScroll.ts
  src/pages/restaurant/RestaurantSemesterMeal.tsx
  src/pages/restaurant/RestaurantWeekendMeal.tsx
  src/services/customAxios.ts
  src/types/restaurant.d.ts
  src/utils/formatCurrency.ts
  src/utils/formatPhoneNum.ts
  src/utils/getDayOfWeek.ts
  src/utils/regex.ts
  src/utils/timer.ts
  src/utils/validate.ts
Labels: ✨ Feat

#46 refactor: 無限ローディング問題を解決
  src/components/auth/LoginForm.tsx
  src/pages/Main.tsx
Labels: ♻ Refactor

#47 refactor: リフレッシュトークンのリファクタリング
  src/components/auth/LoginForm.tsx
  src/services/customAxios.ts
Labels: ♻ Refactor

#48 Deploy: v0.0.1
  src/components/Header.tsx
  src/components/auth/GetResult.tsx
  src/components/auth/LoginForm.tsx
  src/components/mypage/PasswordConfirmation.1.tsx
  src/components/restaurant/SemesterMeal.tsx
  src/components/restaurant/main/WeekendApplication.tsx
  src/components/restaurant/main/applicationSet/ApplicationSettings.tsx
  src/components/restaurant/main/applicationSet/ManualSettings.tsx
  src/components/restaurant/main/applicationSet/SemesterManualSettings.tsx
  src/components/restaurant/main/applicationSet/WeekendManualSettings.tsx
  src/components/restaurant/semesterStatus/SemesterList.tsx
  src/components/restaurant/semesterStatus/SemesterMeal.tsx
  src/components/restaurant/weekendStatus/WeekendList.tsx
  src/components/restaurant/weekendStatus/WeekendMeal.tsx
  src/hook/useSideScroll.ts
  src/pages/Main.tsx
  src/pages/restaurant/RestaurantSemesterMeal.tsx
  src/pages/restaurant/RestaurantWeekendMeal.tsx
  src/services/customAxios.ts
  src/types/restaurant.d.ts
  src/utils/formatCurrency.ts
  src/utils/formatPhoneNum.ts
  src/utils/getDayOfWeek.ts
  src/utils/regex.ts
  src/utils/timer.ts
  src/utils/validate.ts
Labels: 📦 Deploy

#49 feat: メインページのアクセス権に応じたページ遷移機能を追加, Design: アプリケーション全体のフォント変更
  src/pages/Main.tsx
  src/styles/index.css
Labels: ✒ Design, ✨ Feat

#50 chore: 口座設定フォームの名前を変更
  src/components/restaurant/main/applicationSet/AccountSettings.tsx
Labels: 🖍 Chore

#52 Deploy: v0.0.2
  src/components/restaurant/main/applicationSet/AccountSettings.tsx
  src/pages/Main.tsx
  src/services/customAxios.ts
  src/styles/index.css
Labels: 📦 Deploy

#54 Deploy: v0.0.3
  src/services/customAxios.ts
Labels: 📦 Deploy

#55 feat: 食事申込の入金状況修正機能を追加
  src/components/restaurant/semesterStatus/SemesterList.tsx
  src/components/restaurant/weekendStatus/WeekendList.tsx
Labels: ✨ Feat

#56 Design: ファビコン画像を追加
  public/favicon.ico
  public/index.html
  src/components/salon/PriceTag.tsx
Labels: ✒ Design

#57 Release/1.0.0
  public/favicon.ico
  public/index.html
  src/components/restaurant/semesterStatus/SemesterList.tsx
  src/components/restaurant/weekendStatus/WeekendList.tsx
  src/components/salon/PriceTag.tsx
Labels: 📦 Release

#58 Fix: htmlエラーを解決
  public/index.html
Labels: 🐛 Fix

#59 Release/1.0.1
  public/index.html
Labels: 📦 Release

#60 refactor: イメージのサイズを変更しました。
  src/components/admin/as/ReadAS.tsx
  src/components/post/PostCardSlider.tsx
  src/components/restaurant/dietPlan/DietPlanManagement.tsx
  src/components/restaurant/dietPlan/ExcelCard.tsx
  src/components/restaurant/dietPlan/ModalAddPlan.tsx
Labels: ♻ Refactor

#61 refactor: イメージのサイズを変更しました。
  src/components/admin/as/ReadAS.tsx
  src/components/post/PostCardSlider.tsx
  src/components/restaurant/dietPlan/DietPlanManagement.tsx
  src/components/restaurant/dietPlan/ExcelCard.tsx
  src/components/restaurant/dietPlan/ModalAddPlan.tsx
Labels: ♻ Refactor
