Repository Shining-Jicheon-Stars/yjg-ts-react-frontend, pull requests merged in 2024-05, with the labels that each got.

#62 refactor: React Queryを適用してログイン関連ロジックを改善
  package-lock.json
  package.json
  src/components/auth/AuthBg.tsx
  src/components/auth/FindMyAccountForm.tsx
  src/components/auth/GetResult.tsx
  src/components/auth/GoLogin.tsx
  src/components/auth/JoinForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/restaurant/dietPlan/ModalAddPlan.tsx
  src/index.tsx
  src/recoil/UserDataAtiom.tsx
  src/types/auth.d.ts
Labels: ♻ Refactor

#63 refactor: 「マイページ」ロジックにReact Queryを適用
  src/components/auth/FindMyAccountForm.tsx
  src/components/auth/JoinForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/mypage/MypageForm.tsx
  src/components/mypage/PasswordConfirmation.1.tsx
  src/components/mypage/PasswordConfirmation.tsx
Labels: ♻ Refactor

#64 refactor: サイドバーモーダルのロジック変更
  src/components/sidebar/SidePowerModal.tsx
  src/components/sidebar/Sidebar.tsx
  src/constants/powerList.tsx
  src/routes/AdminRoutes.tsx
  src/routes/MasterRoutes.tsx
  src/routes/RestaurantRoutes.tsx
  src/routes/SalonRoutes.tsx
  src/types/sidebarList.d.ts
Labels: ♻ Refactor

#65 feat: recoil persist ライブラリを追加
  package-lock.json
  package.json
  src/components/auth/LoginForm.tsx
  src/constants/powerList.tsx
  src/pages/Main.tsx
  src/pages/Mypage.tsx
  src/recoil/UserDataAtiom.tsx
  src/routes/ProtectedRoute.tsx
Labels: ✨ Feat

#66 refactor: React Queryを適用して 総管理者ページのロジックを改善
  src/components/admin/as/ReadAS.tsx
  src/components/admin/as/RepairList.tsx
  src/components/admin/bus/BusCategoryList.tsx
  src/components/admin/bus/BusManagement.tsx
  src/components/admin/bus/BusScheduleList.tsx
  src/components/admin/main/AdminMain.tsx
  src/components/admin/main/ModifyPost.tsx
  src/components/admin/main/ReadPost.tsx
  src/components/admin/main/WritePost.tsx
  src/components/admin/overNight/CheckStay.tsx
  src/components/admin/overNight/ReadAbsence.tsx
  src/components/admin/room/RoomReservation.tsx
  src/components/auth/GetResult.tsx
  src/components/master/CheckPower.tsx
  src/components/master/MasterMain.tsx
  src/components/master/OverallUser.tsx
  src/components/mypage/MypageForm.tsx
  src/components/mypage/PasswordConfirmation.tsx
  src/components/restaurant/dietPlan/DietPlanManagement.tsx
  src/components/restaurant/dietPlan/ModalAddPlan.tsx
  src/components/restaurant/main/applicationSet/AccountSettings.tsx
  src/components/restaurant/main/applicationSet/SemesterManualSettings.tsx
  src/components/restaurant/main/applicationSet/WeekendManualSettings.tsx
  src/components/restaurant/semesterStatus/SemesterList.tsx
  src/components/restaurant/semesterStatus/SemesterMeal.tsx
  src/components/restaurant/weekendStatus/WeekendList.tsx
  src/components/restaurant/weekendStatus/WeekendMeal.tsx
  src/components/salon/PriceCorrection.tsx
  src/components/salon/ReservationList.tsx
  src/components/salon/SalonCategoryList.tsx
  src/components/salon/SalonServiceList.tsx
  src/components/salon/SetBusinessTime.tsx
  src/components/salon/UnreservedList.tsx
  src/components/table/Table.tsx
  src/pages/master/Management.tsx
  src/pages/master/Master.tsx
  src/pages/master/NotApproved.tsx
  src/routes/MasterRoutes.tsx
Labels: ♻ Refactor, 💱Rename

#67 refactor: 管理関連ページのロジックをReact Queryを活用してリファクタリング
  src/components/admin/as/ReadAS.tsx
  src/components/admin/as/RepairList.tsx
  src/components/admin/bus/BusCategoryList.tsx
  src/components/admin/bus/BusManagement.tsx
  src/components/admin/bus/BusScheduleList.tsx
  src/components/admin/main/WritePost.tsx
  src/components/admin/notice/ModifyPost.tsx
  src/components/admin/notice/ReadPost.tsx
  src/components/admin/overNight/CheckStay.tsx
  src/components/admin/overNight/ReadAbsence.tsx
  src/components/admin/room/RoomReservation.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/BusTimeTable.tsx
  src/pages/admin/MeetingRoom.tsx
  src/pages/admin/Notice.tsx
  src/pages/admin/Repair.tsx
  src/pages/admin/StayOut.tsx
  src/pages/post/Modifying.tsx
  src/pages/post/Reading.tsx
  src/pages/post/Writing.tsx
  src/routes/AdminRoutes.tsx
  src/types/admin.d.ts
Labels: ♻ Refactor

#68 refactor: 美容室ページと料水ページのロジックをリファクタリング, feat: 料水ページに食事メニューの追加機能を実装
  src/components/admin/as/RepairList.tsx
  src/components/admin/bus/BusCategoryList.tsx
  src/components/admin/notice/ModifyPost.tsx
  src/components/restaurant/dietPlan/DietPlanManagement.tsx
  src/components/restaurant/dietPlan/ExcelCard.tsx
  src/components/restaurant/dietPlan/ModalAddPlan.tsx
  src/components/restaurant/main/RestaurantMain.tsx
  src/components/restaurant/main/applicationSet/AccountSettings.tsx
  src/components/restaurant/semesterStatus/SemesterMeal.tsx
  src/components/restaurant/weekendStatus/WeekendMeal.tsx
  src/components/salon/PriceCorrection.tsx
  src/components/salon/UnreservedList.tsx
  src/pages/admin/BusTimeTable.tsx
  src/pages/restaurant/Restaurant.tsx
  src/pages/restaurant/RestaurantDietPlan.tsx
  src/pages/restaurant/RestaurantSemesterMeal.tsx
  src/pages/restaurant/RestaurantWeekendMeal.tsx
  src/pages/salon/ReservationList.tsx
  src/pages/salon/Salon.tsx
  src/pages/salon/SalonPending.tsx
  src/pages/salon/SalonPrice.tsx
  src/routes/SalonRoutes.tsx
  src/types/restaurant.d.ts
Labels: ✨ Feat, ♻ Refactor

#69 Fix: ナビゲーションアドレスの変更
  src/assets/schoolImg/dormitoryImg.jpg
  src/assets/schoolImg/test.jpg
  src/assets/winter.jpg
  src/components/Header.tsx
  src/components/MainBg.tsx
  src/components/admin/notice/ReadPost.tsx
  src/constants/powerList.tsx
  src/pages/Main.tsx
  src/pages/post/Writing.tsx
  src/pages/restaurant/RestaurantQRCheck.tsx
  src/routes/RestaurantRoutes.tsx
Labels: 🐛 Fix

#72 Fix: Mergeエラーを解決
  release-note.md
Labels: 🐛 Fix
