Repository Shining-Jicheon-Stars/yjg-ts-react-frontend, pull requests merged in 2024-03, with the labels that each got.

#26 Refactor: ユーザーリストテーブルのリファクタリング
  src/App.tsx
  src/components/admin/AdminMain.tsx
  src/components/admin/CheckStay.tsx
  src/components/admin/RepairList.tsx
  src/components/master/MasterMain.tsx
  src/components/master/OverallUser.tsx
  src/components/master/UserList.tsx
  src/components/post/PostCardSlider.tsx
  src/components/salon/CateGoryList.tsx
  src/components/salon/ReservationList.tsx
  src/components/salon/ServiceList.tsx
  src/components/salon/UnreservedList.tsx
  src/pages/master/Master.tsx
  src/types/master.d.ts
Labels: ♻ Refactor

#28 Feat: 権限ごとのルート設定と404ページの追加
  src/App.tsx
  src/components/admin/AdminMain.tsx
  src/components/post/ReadPost.tsx
  src/pages/NotFound.tsx
  src/recoil/UserDataAtiom.tsx
  src/routes/AdminRoutes.tsx
  src/routes/MasterRoutes.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/RestaurantRoutes.tsx
  src/routes/Routing.tsx
  src/routes/SalonRoutes.tsx
  src/types/auth.d.ts
Labels: ✨ Feat, ♻ Refactor

#29 行政関連ページを追加, ルーティング構造をリファクタリング, 修正されたAPIエンドポイントのアドレスを更新
  src/components/Header.tsx
  src/components/admin/AdminMain.tsx
  src/components/admin/BusManagement.tsx
  src/components/admin/CheckStay.tsx
  src/components/admin/RepairList.tsx
  src/components/admin/RoomReservation.tsx
  src/components/admin/as/ReadAS.tsx
  src/components/admin/as/RepairList.tsx
  src/components/admin/bus/BusCategoryList.tsx
  src/components/admin/bus/BusManagement.tsx
  src/components/admin/bus/BusScheduleList.tsx
  src/components/admin/bus/ChoiceList.tsx
  src/components/admin/main/AdminMain.tsx
  src/components/admin/main/ModifyPost.tsx
  src/components/admin/main/ReadPost.tsx
  src/components/admin/main/WritePost.tsx
  src/components/admin/overNight/CheckStay.tsx
  src/components/admin/overNight/ReadAbsence.tsx
  src/components/admin/room/RoomReservation.tsx
  src/components/admin/room/RoomState.tsx
  src/components/auth/JoinForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/master/MasterMain.tsx
  src/components/master/OverallUser.tsx
  src/components/mypage/MypageForm.tsx
  src/components/post/Editor.tsx
  src/components/post/page/SearchBar.tsx
  src/components/salon/CountCard.tsx
  src/components/salon/PriceCorrection.tsx
  src/components/salon/PriceTag.tsx
  src/components/salon/ReservationList.tsx
  src/components/salon/SalonCategoryList.tsx
  src/components/salon/SalonServiceList.tsx
  src/components/salon/UnreservedList.tsx
  src/components/sidebar/Sidebar.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/BusTimeTable.tsx
  src/pages/admin/MeetingRoom.tsx
  src/pages/admin/Repair.tsx
  src/pages/admin/StayOut.tsx
  src/pages/master/Management.tsx
  src/pages/post/Modifying.tsx
  src/pages/post/Reading.tsx
  src/pages/post/Writing.tsx
  src/routes/AdminRoutes.tsx
  src/routes/Routing.tsx
  src/services/customAxios.ts
  src/types/admin.d.ts
  src/types/auth.d.ts
  src/types/post.d.ts
  src/types/salon.d.ts
Labels: ✨ Feat, ♻ Refactor

#30 Chore: build関連ファイル生成
  buildspec.yml
  imagedefinitions.json
Labels: ✨ Feat

#32 Feat: 会議室予約拒否, 美容室の営業時間設定, 食事メニュー
  src/assets/cook.png
  src/assets/excel.png
  src/assets/winter.jpg
  src/components/admin/room/RoomReservation.tsx
  src/components/auth/LoginForm.tsx
  src/components/post/page/SearchBar.tsx
  src/components/restaurant/SemesterMeal.tsx
  src/components/restaurant/WeekendMeal.tsx
  src/components/restaurant/dietPlan/DietPlanManagement.tsx
  src/components/restaurant/dietPlan/ExcelCard.tsx
  src/components/restaurant/dietPlan/ModalAddPlan.tsx
  src/components/restaurant/main/ApplicationSettings.tsx
  src/components/restaurant/main/RestaurantMain.tsx
  src/components/restaurant/main/TodayPlan.tsx
  src/components/restaurant/main/WeekendApplication.tsx
  src/components/salon/CountCard.tsx
  src/components/salon/PriceCorrection.tsx
  src/components/salon/SetBusinessTime.tsx
  src/components/salon/UnreservedList.tsx
  src/constants/powerList.tsx
  src/icons/PlusIcon.tsx
  src/pages/restaurant/Restaurant.tsx
  src/pages/restaurant/RestaurantDietPlan.tsx
  src/pages/restaurant/RestaurantSemesterMeal.tsx
  src/pages/restaurant/RestaurantWeekendMeal.tsx
  src/routes/RestaurantRoutes.tsx
  src/types/restaurant.d.ts
  src/types/salon.d.ts
Labels: ✨ Feat, ♻ Refactor

#33 Chore: docker関連ファイルを生成
  Dockerfile
  nginx.conf
Labels: ✨ Feat

#34 Chore: デプロイのためのファイルを生成
  Dockerfile
  nginx.conf
  taskdef.json
Labels: ✨ Feat

#35 Chore: appspec.ymlを生成
  appspec.yml
Labels: ✨ Feat

#36 Chore: taskdef.jsonを修正
  taskdef.json
Labels: ♻ Refactor
